[language-server.simple-token]
# command = "simple-token-language-server"
command = "/Users/freddie/Documents/simple-token-language-server/target/debug/simple-token-language-server"
args= ["--spell"]


[[language]]
name="rust"
language-servers = [ "rust-analyzer" , "simple-token"]
